--TAO 6 USER
CREATE LOGIN USER1 WITH PASSWORD = '123456'
CREATE LOGIN USER2 WITH PASSWORD = '123456'
CREATE LOGIN USER3 WITH PASSWORD = '123456'
CREATE LOGIN USER4 WITH PASSWORD = '123456'
CREATE LOGIN USER5 WITH PASSWORD = '123456'
CREATE LOGIN USER6 WITH PASSWORD = '123456'

-- TAO 6 DATABASE USER
CREATE USER U1 FOR LOGIN USER1
CREATE USER U2 FOR LOGIN USER2
CREATE USER U3 FOR LOGIN USER3
CREATE USER U4 FOR LOGIN USER4
CREATE USER U5 FOR LOGIN USER5
CREATE USER U6 FOR LOGIN USER6

--TAO ROLE 
CREATE ROLE R1 
CREATE ROLE R2 
CREATE ROLE R3

--THEM USER VAO NHOM 
EXEC sp_addrolemember R1, U1
EXEC sp_addrolemember R2, U2
EXEC sp_addrolemember R2, U3
EXEC sp_addrolemember R3, U4
EXEC sp_addrolemember R3, U5
EXEC sp_addrolemember R3, U6

--CAP QUYEN
GRANT SELECT, DELETE ON GIAOVIEN TO U1
GRANT SELECT, DELETE ON SINHVIEN TO U1
GRANT UPDATE, DELETE ON DETAI TO U2
GRANT INSERT ON GIAOVIEN TO U3
GRANT INSERT ON DETAI TO U3	
GRANT INSERT ON SINHVIEN TO U3	
DENY INSERT ON GIAOVIEN TO U1
DENY INSERT ON DETAI TO U1
DENY DELETE ON SINHVIEN TO U2 
